#include <sndfile.h>
#include <stdio.h>

int main(int argc, char **argv)
{
    SF_INFO info;
    SNDFILE *file;
    short buf[4096];
    char *name = NULL;
    int len, j, cnt = 0;

    if (argc == 2) {
        name = argv[1];
    } else {
        name = "sample";
    }

    if ( !(file = sf_open("-", SFM_READ, &info)) ) {
        fprintf(stderr, "sf_open: %s\n", sf_strerror(file));
        exit(1);
    }

    printf("/* This file was automaticly generated by `%s'\n"
           "    don't edit it by hand, all changes will be lost ;)\n"
           "    This file contains %s audio sample, rate %d\n"
           "    Usage: convert [name] < foo.wav > foo.h */\n",
            argv[0], info.channels > 1? "stereo" : "mono", info.samplerate);
    printf("prog_uchar %s [] = {\n", name);

    while ( (len = sf_read_short(file, buf, sizeof(buf)/sizeof(buf[0]))) > 0) {
        int i;

        for (i = 0; i < len; i++) {
            printf("\t0x%02x,%c", (buf[i] >> 8) + 128, (++j & 7)? ' ' : '\n');
        }
        cnt += len;
    }

    printf("\n} ;\n\n");
    fprintf(stderr, "%d frames processed.\n", cnt);

    return 0;
}
