#!/bin/sh

exec > samples.h

cat <<EOF
/*
 * Warning!! This file was automaticly generated by $0
 * Edit $0 and $* instead ;)
 */
#ifndef _samples_h_
#define _samples_h_

#include <avr/pgmspace.h>

EOF

n=0
for i in $*; do
    echo "#undef sample"
    echo "#define sample sample$n"
    echo "#include \"$i\""
    n=$((++n))
done

cat <<EOF
#undef sample

struct {
    PGM_P sample;
    unsigned short len;
} samples [] = {
EOF

n=0
for i in $*; do
    echo "	{ sample$n, sizeof(sample$n) }, "
    n=$((++n))
done


cat <<EOF
} ;
#endif /* _samples_h_ */
EOF
